apiVersion: kosmos.io/v1alpha1
kind: Cluster
metadata:
  name: member-cluster
spec:
  cni: "calico"
  defaultNICName: eth0
  imageRepository: {{ .image-repository }} # Default: ghcr.io/kosmos-io
  networkType: {{ .network-type }} # Optional: gateway/p2p